# Welcome to Jekyll!
#

# Site settings
title: Utopian Lab
description: |
  We believe in the inner potential of organizations. Everything we do, 
  we believe in doing things allowing for impacting the people who we work with.
  We help organizations to see problems from unusual perspectives and We help them to 
  create products and services allowing them for making decisions on behalf of their 
  customer needs. As result, We use strategic planning, data analysis, and knowledge 
  transference as way to achieve such goal
owner: Utopian Lab # or company name
first_published: 2019 # if migrating another site, the year of your first publish
email: alexisrodgtz@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://utopianlab.co" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
